Added tng format
MDverse/mdws pull request #18
Opened 2022-05-30 17:40 UTC by GiovanniBussi

See [https://manual.gromacs.org/current/manual-2022.1.pdf], page 26:
```
Trajectory file (.trr, .tng, or .xtc)
```

2022-06-01 21:36 UTC, j0kaso requested changes
good catch! I did a quick check and didn't found a datasets on zenodo/figshare that have a tng file though. But might be added in the future.

2022-06-01 21:36 UTC, j0kaso commented on params/query.yml
> +  keywords: none
I did a quick check and could not find any files for tng. therefore, I would use a more conservative search strategy and add some keywords (e.g. generic_keywords)

2022-06-02 07:22 UTC, GiovanniBussi commented
I also never used it, just saw it advertised on GROMACS doc since several years..

2022-06-02 07:53 UTC, pierrepo reviewed
Thanks @GiovanniBussi

2022-06-02 07:54 UTC, pierrepo approved these changes

2022-06-02 07:55 UTC, pierrepo commented
@j0kaso I will indeed the `generic_keywords` as a safeguard

2022-06-02 07:56 UTC, merged